global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "service-a"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-a:3001"]

  - job_name: "service-b"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-b:3002"]

  - job_name: "service-c"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-c:3003"]
