limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;

log_format json_logs escape=json '{'
  '"timestamp":"$time_iso8601",'
  '"request_id":"$http_x_request_id",'
  '"method":"$request_method",'
  '"path":"$request_uri",'
  '"status":$status,'
  '"upstream":"service-a:3001",'
  '"request_time":$request_time,'
  '"remote_addr":"$remote_addr",'
  '"body_bytes_sent":$body_bytes_sent'
'}';

server {
    listen 80;
    server_name _;
resolver 127.0.0.11 valid=10s;
    access_log /var/log/nginx/service-proxy-access.log json_logs;
    error_log /var/log/nginx/service-proxy-error.log;

    location /service-a/ {
    limit_req zone=api_limit burst=10 nodelay;

    resolver 127.0.0.11 valid=10s;
    set $service_a http://service-a:3001;

    rewrite ^/service-a/(.*)$ /$1 break;
    proxy_pass $service_a;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Request-ID $http_x_request_id;
    proxy_read_timeout 15s;
    proxy_connect_timeout 5s;
}

    location / {
        default_type application/json;
        return 404 '{"error": "Not found", "message": "Only /service-a/* routes are available"}';
    }
}
